// layout.tsx
import type { Metadata } from "next";
import "./globals.css"; 
import Sidebar from "../components/Sidebar"; 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Sidebar /> 
        <div className="ml-64 flex min-h-screen"> 
          <main className="min-h-screen"> 
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
